# Generated by Django 4.0.4 on 2022-05-09 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employers',
            name='experience',
            field=models.CharField(default=123, max_length=20),
            preserve_default=False,
        ),
    ]
